# Generated by Django 5.1.2 on 2024-11-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("duration", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("prerequisites", models.TextField()),
                ("instructors", models.JSONField()),
                ("modules", models.JSONField()),
                (
                    "pdf_url",
                    models.FileField(blank=True, null=True, upload_to="syllabi/"),
                ),
            ],
        ),
    ]
