# Generated by Django 5.1.2 on 2024-11-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="UserQuery",
        ),
    ]
